- name: Configure Minecraft Server
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Check that Docker is running
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Create a Docker container for the Minecraft server
      docker_container:
        name: minecraft
        image: itzg/minecraft-server
        state: started
        restart_policy: always
        ports:
          - "25565:25565"
        env:
          EULA: "TRUE"
          VERSION: "LATEST"